apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-training
  labels:
    app: docker-training
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-training
  template:
    metadata:
      labels:
        app: docker-training
    spec:
      containers:
      - name: docker-training
        image: tylerlinder/docker-training:latest
        ports:
        - containerPort: 80