apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockertraining
  labels:
    app: dockertraining
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockertraining
  template:
    metadata:
      labels:
        app: dockertraining
    spec:
      containers:
      - name: dockertraining
        image: tylerlinder/docker-training:latest
        ports:
        - containerPort: 80